#!/bin/sh

for i in `seq 5000 1000 10000`
do
	size=$i
	for insert in L A B R S V
	do
		for order in A P R
		do
			echo ""
			echo "Test: ./tlab $size $order $insert"
			echo "t" | ./tlab $size $order $insert | grep -v Tree
		done
	done
done
